### PR TITLE
Import existing examples from Dyninst

### PR DESCRIPTION
**Pull request by hainest**
I've updated the codeCoverage example to a format that will build nicely and produce usable results.

@MandrakeCQC @kerenchen When one (or both) of you finishes working on your current task, could you take a look at the unstrip example here and update it like I did with the codeCoverage one?

### CODE REVIEW

**Comment by hainest** [comment]
@ bbiiggppiigg I've added some instructions for building/running. Could you try them and see if you can get the codeCoverage example to work for you?

**Comment by bbiiggppiigg** [comment]
codeCoverage still don' work for me.

After commenting out LanguageStandards and optimization (which I don't have, maybe is some dependency installed?), I get to the point where cmake tries to link the final binary, but there is this error about linking boost_system

... undefined reference to symbol '_ZN5boost6system15system_categoryEv'
... dyninst/lib/libboost_system.so.1.61.0: error adding symbols: DSO missing from command line

In the original CMakeLists.txt(dyninst/examples/CMakeLists.txt), there are far more depedencies and target_link than what you have now.
`
add_dependencies(codeCoverage dyninstAPI patchAPI parseAPI symtabAPI instructionAPI pcontrol common stackwalk dynDwarf dynElf)
 32 target_link_libraries(codeCoverage dyninstAPI patchAPI parseAPI symtabAPI instructionAPI pcontrol common stackwalk dynDwarf dynElf ${Boost_LIBRARIES} ${ElfUtils_LIBRARIES}) 
`

I tried to modify your CMakeLists.txt to comply with these, but I still get the same error.

**Comment by hainest** [comment]
>After commenting out LanguageStandards and optimization (which I don't have, maybe is some dependency installed?)

They were added after the 10.1 release. You'll need to build from the head of master to get them.

>In the original CMakeLists.txt(dyninst/examples/CMakeLists.txt), there are far more depedencies and target_link than what you have now.

Dyninst's dependencies are now transitively linked because they are RPATH'd. I believe this is also a post-10.1 update.

**Comment by hainest** [comment]
@bbiiggppiigg I couldn't get the "instrumentMemoryAccess" example to work. I did

    $ cmake ...
    $ make
    $ export DYNINSTAPI_RT_LIB=...
    $ ln -s ../InterestingProgram .
    $ ./instrumenting_memory_access

but I always get the error

    --FATAL-- #68: Dyninst was unable to create the specified process
    --FATAL-- #68: create process failed bootstrap
    processCreate failed
    startInstrumenting failed

Could you take a look, and push any updates to this branch?

**Comment by bbiiggppiigg** [comment]
@hainest 
The example works on my end.
Is the instrument_a_function example also failing or if this is the only example that fails?

As you can see from the error message, the failure occurs at process startup.
However, as the instrument _a_function example and the instrument _memory_access function share the same code for creating a binary to patch, I can't think of a reasonable explanation where one fails but the other doesn't.

Is it possible that you run into some hardware resource limit issue that prevents the system from creating the mutatee process to be inspected ?
I'll try to recompile dyninst with debug_startup set to true but as I'm not able to reproduce your error I probably won't be able to help you with my debug-enabled version of dyninst.

**Comment by kupsch** [comment]
Running cmake 3.10.2 produced the error:
```
CMake Error at codeCoverage/CMakeLists.txt:23 (target_link_options):
  Unknown CMake command "target_link_options".
```
The `cmake_minimum_required` is set to 3.4.0, but `target_link_options` first appeared in cmake 3.13. Using the latest cmake (3.16.8) works successfully.

**Comment by kupsch** [comment]
After fixing cmake, make fails with
```
Scanning dependencies of target InterestingProgram
[  3%] Building CXX object CMakeFiles/InterestingProgram.dir/common/mutatees/InterestingProgram.cpp.o
[  7%] Linking CXX executable InterestingProgram
[  7%] Built target InterestingProgram
Scanning dependencies of target code_coverage
[ 10%] Building CXX object codeCoverage/CMakeFiles/code_coverage.dir/code_coverage.C.o
[ 14%] Linking CXX executable code_coverage
/usr/bin/ld: CMakeFiles/code_coverage.dir/code_coverage.C.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//nobackup/kupsch/dyninst/dyninst/install/lib/libboost_system.so.1.61.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
codeCoverage/CMakeFiles/code_coverage.dir/build.make:87: recipe for target 'codeCoverage/code_coverage' failed
make[2]: *** [codeCoverage/code_coverage] Error 1
CMakeFiles/Makefile2:262: recipe for target 'codeCoverage/CMakeFiles/code_coverage.dir/all' failed
make[1]: *** [codeCoverage/CMakeFiles/code_coverage.dir/all] Error 2
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
```
This is built against the head of dynist/dyninst (commit 73b4b1c3632c9081ffb0e87f1b674cdbff67aacf) on Ubuntu 18.04 with gcc 7.5.0 and ld 2.30.  If I manually add the library libboost_system, it links successfully.

**Comment by bbiiggppiigg** [comment]
@kupsch how did you add libboost_system to the cmake file manually? 
I'm just trying to build the examples on the lab machines and ran into the same problem as yours

**Comment by kupsch** [comment]
Using `make VERBOSE=1`, I ran the command
```
/usr/bin/c++  -O2 -g    CMakeFiles/code_coverage.dir/code_coverage.C.o  -o code_coverage  -Wl,-rpath,/nobackup/kupsch/dyninst/dyninst/install/lib /nobackup/kupsch/dyninst/dyninst/install/lib/libdyninstAPI.so.10.1.0 /nobackup/kupsch/dyninst/dyninst/install/lib/libboost_system.so
```
/nobackup/kupsch/dyninst/dyninst/install is where I installed dyninst.

**Comment by kupsch** [comment]
I also did a `cd codeCoverage` prior to running c++

**Comment by bbiiggppiigg** [comment]
@kupsch I've created a new pull request #6  that should fix the problem of not being able to link to boost directory, can you check if that works for you ?

@hainest after fixing the cmake + boost issue, I'm able to get the memory access example to run on orion. 
The path to my build is /p/paradyn/development/wuxx1279/examples/build/instrumentMemoryAccess, you

Commands for compile+ execution:
export DYNINST_ROOT= what ever
`mkdir build`
`cd build`
`cake ..`
`make install -j8`
`cd instrumentMemoryAccess`
`ln -s ../interestingProgram .`
`./instrument_memory_access`

**Comment by kupsch** [comment]
@bbiiggppiigg did you push these changes on the branch. The last update to this repo was June 14.

**Comment by bbiiggppiigg** [comment]
@kupsch 
I just merged it so you can test it. But I'm thinking that maybe I shouldn't have done that.
I was hoping that you can fetch from the pull request from my repo and test it before it is merged.

**Comment by kupsch** [comment]
@bbiiggppiigg builds successfully now.

**Comment by bbiiggppiigg** [comment]
@hainest starting from boost 1.69 (https://www.boost.org/users/history/version_1_69_0.html)
Boost symbols are compiled with default visibility = hidden, so If we use any version later than that, we don't need to link boost in our examples at all. 
I tested this with my boost v1.71  and they compile just fine.

**Comment by hainest** [comment]
@bbiiggppiigg Ah, that may also be part of it. I use Boost 1.73.

**Comment by hainest** [comment]
@bbiiggppiigg @MandrakeCQC @MandrakeCQC @kupsch Could you try building the current changes?

**Comment by bbiiggppiigg** [comment]
@hainest 
There is a bug in the top level CMakelist
It seems like on line 28 and 29, either you want to use _dyninst_dir 
or you want to set $Dyninst_DIR to _dyninst_dir
As you are always updating the _dyninst_dir variable instead of $Dyninst_DIR

**Comment by kupsch** [comment]
Everything builds without issue for me using a stock Ubuntu 18 host plus cmake 3.16.8. I built the head of the branch import_examples of the repo examples with the head of the branch master master of repo dyninst.

**Comment by hainest** [comment]
@bbiiggppiigg Good catch! I didn't notice it because I always set Dyninst_DIR on the command line when invoking cmake. Does it work for you now?

**Comment by bbiiggppiigg** [comment]
@hainest yes, it works now.

**Pull request merged**
