### PR TITLE
Include existing examples from the dynisntAPI manual appendex and maxArg

### PR DESCRIPTION
**Pull request by bbiiggppiigg**
I can't get your examples in the import_example  branch to work
Here are the examples that can compile assuming dyninst is installed and 
DYNINST_ROOT, DYNINST_RT_LIB, and LD_LIBRARY_PATH set correctly

As three of the examples share the same mutatee, I created symbolic link in these sub-directories instead.

### CODE REVIEW

**Comment by hainest** [comment]
As I noted earlier, we'll want to convert these to use CMake, but getting them running is a big first step.

>As thee of the examples share the same mutatee, I created symbolic link in these sub-directories instead.

Let's make a top-level directory for shared libraries/mutatees. Something like "common/mutatees". Then we can use CMake to tie them together.

**Comment by bbiiggppiigg** [comment]
I had a commit in the original dyninst that can build examples with cmake__

https://github.com/dyninst/dyninst/pull/760/commits/96e20a969850039e28e9206d190de9fc55115eff

But I don't know how to make it work when the examples folder is separated out.
Can you build the examples in your import_examples branch using CMake ? 

I set the Dyninst_DIR to /path/to/dyninst/build/CMakeFiles,
and CMake complains that Dyninst_FOUND is set to FALSE, so Dyninst is considered to be NOT FOUND.

This is because according these lines in DyninstConfig.cmake, dyninstAPI is not the TARGET
` 
40 if(TARGET dyninstAPI)
41   set(Dyninst_FOUND 1)
42 else()
43   set(Dyninst_FOUND 0)
44 endif()
`
And I'm not sure how to procede.

**Comment by hainest** [comment]
>I set the Dyninst_DIR to /path/to/dyninst/build/CMakeFiles

That should be `/path/to/dyninst/lib/dyninst/cmake/Dyninst`. Confusingly, `Dyninst_DIR` should point to the custom CMake install directory where all of Dyninst's CMake files are copied on installation.

**Comment by bbiiggppiigg** [comment]
So I fixed an issue with the top level CMake, and now all examples are built using CMake.
The shared mutatee is located under common/mutatees

**Comment by hainest** [comment]
Merged into #3

**Pull request closed without merging**
